const NavData = {
  men: {
    TopWear: [
      "t-shirt",
      "casual-shirt",
      "formal-shirt",
      "sweatShirt",
      "sweater",
      "jacket",
      "blazer & coat",
      "suits",
      "rain jackets",
    ],
    "Indian & Festival Wear": [
      "kurta & kurta sets",
      "sherwanis",
      "nehru jackets",
      "dhotis",
    ],
    bottomwear: [
      "jeans",
      "casual-trousers",
      "formal-trousers",
      "shorts",
      "track pants & joggers",
    ],
    "innerwear & sleepwear": [
      "brief & trunks",
      "boxer",
      "vests",
      "sleepwear & loungewear",
      "thermal",
    ],
    "plus size": [],

    footwear: [
      "casual-shoes",
      "Sport-shoe",
      "formal-shoes",
      "sneakers",
      "sandals & floaters",
      "flip flop",
      "shocks",
    ],
    "personal care & grooming": [],
    "sunglasses & frames": [],
    watches: [],
    "sport & active wear": [
      "sport-shoes",
      "Sport-sandal",
      "active-tshirts",
      "track pants & shoes",
      "tracksuits",
      "jackets & sweartshirt",
      "sport accessories",
      "swimwear",
    ],
    gadgets: ["smart wearables", "futness gadgets", "headphones", "speakers"],
    "fashion accessories": [
      "wallets",
      "belts",
      "perfumes & body mist",
      "trimmers",
      "deodrant",
      "ties,cufflnks & pockets squares",
      "accessort gift sets",
      "caps & hats",
      "mufflers,scarves & gloves ",
      "phone cases",
      "rings & wristwear",
      "helmets",
    ],
    "bags & backpacks": [],
    "luggages & trolleys": [],
  },
  women: {
    "Indian & Fusion Wear": [
      "Kurtas & Suits",
      "Kurtis, Tunics & Tops",
      "Ethnic Wear",
      "Leggings, Salwars & Churidars",
      "Skirts & Palazzos",
      "Sarees",
      "Dress Materials",
      "Lehenga Cholis",
      "Dupattas & Shawls",
      "Jackets",
    ],
    "Belts, Scarves & More": [],
    "Watches & Wearables": [],
    "Western Wear": [
      "Western Wear",
      "Jumpsuits",
      "Tops",
      "Jeans",
      "Trousers & Capris",
      "Shrugs",
      "Sweaters & Sweatshirts",
      "Jackets & Coats",
      "Blazers & Waistcoats",
    ],
    "Plus Size": [],
    "Sunglasses & Frames": [],
    Footwear: [
      "Flats",
      "Casual Shoes",
      "Heels",
      "Boots",
      "Sports Shoes & Floaters",
    ],
    "Sports & Active Wear": [
      "Clothing",
      "Footwear",
      "Sports Accessories",
      "Sports Equipment",
    ],
  },
};
